version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update; apt install nodejs

workflows:
    version: 2.1
    build:
        jobs:
        - trial
